Refactor and improve code in rabbit-worker.js
projectcypress/js-ecqm-engine pull request #20
Opened 2018-07-10 14:57 UTC by okeefm

* Refactor environment variable/command line variable parsing using `convict`: https://github.com/mozilla/node-convict
* Try the RabbitMQ Connection 6 times (The initial connection attempt + 5 retries) over the course of ~1-2 minutes,  with exponential backoff.
* Return a `status` variable, saying whether the calculation was successful or failed. Also return an `error` variable, which tells you what the error was (if one was returned).

Should be merged in conjunction with https://github.com/projectcypress/cypress/pull/1016

Pull requests into js-ecqm-engine require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] Internal ticket for this PR:
- [ ] Internal ticket links to this PR
- [ ] Code diff has been done and been reviewed
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2018-07-11 12:36 UTC, rbclark requested changes
Merging this directly into release will trigger a build against it, meaning that anyone attempting to build a VM will get a bad build. I would suggest we merge this into the master branch and only merge into release when we merge into cypress_v4 with the complimentary changes.

2018-07-11 12:39 UTC, okeefm commented
The only problem with that is that `master` doesn't have `bin/rabbit-worker.js` in it yet, so that would have to get merged in first (which it probably should).

2018-07-18 17:57 UTC, rbclark approved these changes

2018-07-19 13:02 UTC, dczulada approved these changes
Looks good

2018-07-19 13:02 UTC, merged